Little = "Little"
Big = "Big"


SIGNED_CHAR = 'b'
UNSIGNED_CHAR = 'B'
LITTLE_ENDIAN_UNSIGNED_INT = '<I'
LITTLE_ENDIAN_SIGNED_INT = '<i'
BIG_ENDIAN_UNSIGNED_INT = '>I'
BIG_ENDIAN_SIGNED_INT = '>i'
STRING = 's'
